In [1]:
import numpy as np

data = np.random.randint(
    1,
    101,
    size=(10, 5)
)

print("2D Random Dataset:")
print(data)

2D Random Dataset:
[[ 15  33  20  20  99]
 [ 27  56  58  34  45]
 [ 65 100  84  93  24]
 [ 53  27  63  71  58]
 [ 86  86  30  20  19]
 [ 58  30  36  81  45]
 [ 13  18 100  49  43]
 [  7  23  60  10  16]
 [ 71  78  97  42  28]
 [  9  89   8  44  81]]
