In [1]:
import numpy as np

# Synthetic 2D Dataset
data = np.array([
    [45, 50, 55, 60, 65],
    [52, 58, 63, 68, 72],
    [67, 70, 75, 78, 82],
    [71, 74, 79, 83, 88],
    [83, 85, 89, 91, 95]
])

print("Dataset:")
print(data)

# Shape and Dimensions
print("\nShape:", data.shape)
print("Number of Dimensions:", data.ndim)
print("Total Elements:", data.size)

# Sum
print("\nSum of All Elements:", np.sum(data))
print("Sum Along Axis 0:", np.sum(data, axis=0))
print("Sum Along Axis 1:", np.sum(data, axis=1))

# Mean
print("\nMean of All Elements:", np.mean(data))
print("Mean Along Axis 0:", np.mean(data, axis=0))
print("Mean Along Axis 1:", np.mean(data, axis=1))

# Median
print("\nMedian of All Elements:", np.median(data))
print("Median Along Axis 0:", np.median(data, axis=0))
print("Median Along Axis 1:", np.median(data, axis=1))

# Minimum
print("\nMinimum of All Elements:", np.min(data))
print("Minimum Along Axis 0:", np.min(data, axis=0))
print("Minimum Along Axis 1:", np.min(data, axis=1))

# Maximum
print("\nMaximum of All Elements:", np.max(data))
print("Maximum Along Axis 0:", np.max(data, axis=0))
print("Maximum Along Axis 1:", np.max(data, axis=1))

# Range
print("\nRange of All Elements:", np.ptp(data))
print("Range Along Axis 0:", np.ptp(data, axis=0))
print("Range Along Axis 1:", np.ptp(data, axis=1))

# Variance
print("\nVariance of All Elements:", np.var(data))
print("Variance Along Axis 0:", np.var(data, axis=0))
print("Variance Along Axis 1:", np.var(data, axis=1))

# Standard Deviation
print("\nStandard Deviation of All Elements:", np.std(data))
print("Standard Deviation Along Axis 0:", np.std(data, axis=0))
print("Standard Deviation Along Axis 1:", np.std(data, axis=1))

# Percentiles
print("\n25th Percentile:", np.percentile(data, 25))
print("50th Percentile:", np.percentile(data, 50))
print("75th Percentile:", np.percentile(data, 75))

print("\n25th Percentile Along Axis 0:", np.percentile(data, 25, axis=0))
print("50th Percentile Along Axis 0:", np.percentile(data, 50, axis=0))
print("75th Percentile Along Axis 0:", np.percentile(data, 75, axis=0))

print("\n25th Percentile Along Axis 1:", np.percentile(data, 25, axis=1))
print("50th Percentile Along Axis 1:", np.percentile(data, 50, axis=1))
print("75th Percentile Along Axis 1:", np.percentile(data, 75, axis=1))

# Quartiles
Q1 = np.percentile(data, 25, axis=0)
Q2 = np.percentile(data, 50, axis=0)
Q3 = np.percentile(data, 75, axis=0)

print("\nQ1 Along Axis 0:", Q1)
print("Q2 Along Axis 0:", Q2)
print("Q3 Along Axis 0:", Q3)

Q1 = np.percentile(data, 25, axis=1)
Q2 = np.percentile(data, 50, axis=1)
Q3 = np.percentile(data, 75, axis=1)

print("\nQ1 Along Axis 1:", Q1)
print("Q2 Along Axis 1:", Q2)
print("Q3 Along Axis 1:", Q3)

# Interquartile Range
print("\nIQR Along Axis 0:", 
      np.percentile(data, 75, axis=0) - np.percentile(data, 25, axis=0))

print("IQR Along Axis 1:", 
      np.percentile(data, 75, axis=1) - np.percentile(data, 25, axis=1))

# Cumulative Sum
print("\nCumulative Sum Along Axis 0:")
print(np.cumsum(data, axis=0))

print("\nCumulative Sum Along Axis 1:")
print(np.cumsum(data, axis=1))

# Cumulative Product
print("\nCumulative Product Along Axis 0:")
print(np.cumprod(data, axis=0))

print("\nCumulative Product Along Axis 1:")
print(np.cumprod(data, axis=1))

# Difference
print("\nDifference Along Axis 0:")
print(np.diff(data, axis=0))

print("\nDifference Along Axis 1:")
print(np.diff(data, axis=1))

# Absolute Deviation from Mean
mean_axis0 = np.mean(data, axis=0)
mean_axis1 = np.mean(data, axis=1)

print("\nAbsolute Deviation from Mean Along Axis 0:")
print(np.abs(data - mean_axis0))

print("\nAbsolute Deviation from Mean Along Axis 1:")
print(np.abs(data - mean_axis1[:, np.newaxis]))

# Mean Absolute Deviation
print("\nMean Absolute Deviation Along Axis 0:")
print(np.mean(np.abs(data - mean_axis0), axis=0))

print("\nMean Absolute Deviation Along Axis 1:")
print(np.mean(np.abs(data - mean_axis1[:, np.newaxis]), axis=1))

# Z-Score Along Axis 0
z_axis0 = (data - np.mean(data, axis=0)) / np.std(data, axis=0)

print("\nZ-Score Along Axis 0:")
print(z_axis0)

# Z-Score Along Axis 1
z_axis1 = (data - np.mean(data, axis=1, keepdims=True)) / np.std(data, axis=1, keepdims=True)

print("\nZ-Score Along Axis 1:")
print(z_axis1)

# Sorting
print("\nSorted Along Axis 0:")
print(np.sort(data, axis=0))

print("\nSorted Along Axis 1:")
print(np.sort(data, axis=1))

# Index of Minimum
print("\nIndex of Minimum Along Axis 0:")
print(np.argmin(data, axis=0))

print("\nIndex of Minimum Along Axis 1:")
print(np.argmin(data, axis=1))

# Index of Maximum
print("\nIndex of Maximum Along Axis 0:")
print(np.argmax(data, axis=0))

print("\nIndex of Maximum Along Axis 1:")
print(np.argmax(data, axis=1))

# Covariance
print("\nCovariance Matrix:")
print(np.cov(data))

print("\nCovariance Matrix of Columns:")
print(np.cov(data, rowvar=False))

# Correlation
print("\nCorrelation Matrix:")
print(np.corrcoef(data))

print("\nCorrelation Matrix of Columns:")
print(np.corrcoef(data, rowvar=False))

Dataset:
[[45 50 55 60 65]
 [52 58 63 68 72]
 [67 70 75 78 82]
 [71 74 79 83 88]
 [83 85 89 91 95]]

Shape: (5, 5)
Number of Dimensions: 2
Total Elements: 25

Sum of All Elements: 1798
Sum Along Axis 0: [318 337 361 380 402]
Sum Along Axis 1: [275 313 372 395 443]

Mean of All Elements: 71.92
Mean Along Axis 0: [63.6 67.4 72.2 76.  80.4]
Mean Along Axis 1: [55.  62.6 74.4 79.  88.6]

Median of All Elements: 72.0
Median Along Axis 0: [67. 70. 75. 78. 82.]
Median Along Axis 1: [55. 63. 75. 79. 89.]

Minimum of All Elements: 45
Minimum Along Axis 0: [45 50 55 60 65]
Minimum Along Axis 1: [45 52 67 71 83]

Maximum of All Elements: 95
Maximum Along Axis 0: [83 85 89 91 95]
Maximum Along Axis 1: [65 72 82 88 95]

Range of All Elements: 50
Range Along Axis 0: [38 35 34 31 30]
Range Along Axis 1: [20 20 15 17 12]

Variance of All Elements: 178.4736
Variance Along Axis 0: [184.64 150.24 143.36 119.6  116.24]
Variance Along Axis 1: [50.   50.24 29.04 37.2  18.24]

Standard Deviation of All Eleme

In [2]:
import numpy as np

# Synthetic 3D Dataset
# Shape: (2, 3, 4)
data = np.array([
    [
        [10, 20, 30, 40],
        [15, 25, 35, 45],
        [20, 30, 40, 50]
    ],
    [
        [12, 22, 32, 42],
        [17, 27, 37, 47],
        [22, 32, 42, 52]
    ]
])

print("Dataset:")
print(data)

# Shape and Dimensions
print("\nShape:", data.shape)
print("Number of Dimensions:", data.ndim)
print("Total Elements:", data.size)

# Sum
print("\nSum of All Elements:", np.sum(data))
print("Sum Along Axis 0:")
print(np.sum(data, axis=0))

print("Sum Along Axis 1:")
print(np.sum(data, axis=1))

print("Sum Along Axis 2:")
print(np.sum(data, axis=2))

# Mean
print("\nMean of All Elements:", np.mean(data))
print("Mean Along Axis 0:")
print(np.mean(data, axis=0))

print("Mean Along Axis 1:")
print(np.mean(data, axis=1))

print("Mean Along Axis 2:")
print(np.mean(data, axis=2))

# Median
print("\nMedian of All Elements:", np.median(data))
print("Median Along Axis 0:")
print(np.median(data, axis=0))

print("Median Along Axis 1:")
print(np.median(data, axis=1))

print("Median Along Axis 2:")
print(np.median(data, axis=2))

# Minimum
print("\nMinimum of All Elements:", np.min(data))
print("Minimum Along Axis 0:")
print(np.min(data, axis=0))

print("Minimum Along Axis 1:")
print(np.min(data, axis=1))

print("Minimum Along Axis 2:")
print(np.min(data, axis=2))

# Maximum
print("\nMaximum of All Elements:", np.max(data))
print("Maximum Along Axis 0:")
print(np.max(data, axis=0))

print("Maximum Along Axis 1:")
print(np.max(data, axis=1))

print("Maximum Along Axis 2:")
print(np.max(data, axis=2))

# Range
print("\nRange of All Elements:", np.ptp(data))
print("Range Along Axis 0:")
print(np.ptp(data, axis=0))

print("Range Along Axis 1:")
print(np.ptp(data, axis=1))

print("Range Along Axis 2:")
print(np.ptp(data, axis=2))

# Variance
print("\nVariance of All Elements:", np.var(data))
print("Variance Along Axis 0:")
print(np.var(data, axis=0))

print("Variance Along Axis 1:")
print(np.var(data, axis=1))

print("Variance Along Axis 2:")
print(np.var(data, axis=2))

# Standard Deviation
print("\nStandard Deviation of All Elements:", np.std(data))
print("Standard Deviation Along Axis 0:")
print(np.std(data, axis=0))

print("Standard Deviation Along Axis 1:")
print(np.std(data, axis=1))

print("Standard Deviation Along Axis 2:")
print(np.std(data, axis=2))

# Percentiles
print("\n25th Percentile:", np.percentile(data, 25))
print("50th Percentile:", np.percentile(data, 50))
print("75th Percentile:", np.percentile(data, 75))

print("\n25th Percentile Along Axis 0:")
print(np.percentile(data, 25, axis=0))

print("50th Percentile Along Axis 0:")
print(np.percentile(data, 50, axis=0))

print("75th Percentile Along Axis 0:")
print(np.percentile(data, 75, axis=0))

print("\n25th Percentile Along Axis 1:")
print(np.percentile(data, 25, axis=1))

print("50th Percentile Along Axis 1:")
print(np.percentile(data, 50, axis=1))

print("75th Percentile Along Axis 1:")
print(np.percentile(data, 75, axis=1))

print("\n25th Percentile Along Axis 2:")
print(np.percentile(data, 25, axis=2))

print("50th Percentile Along Axis 2:")
print(np.percentile(data, 50, axis=2))

print("75th Percentile Along Axis 2:")
print(np.percentile(data, 75, axis=2))

# Cumulative Sum
print("\nCumulative Sum Along Axis 0:")
print(np.cumsum(data, axis=0))

print("\nCumulative Sum Along Axis 1:")
print(np.cumsum(data, axis=1))

print("\nCumulative Sum Along Axis 2:")
print(np.cumsum(data, axis=2))

# Cumulative Product
print("\nCumulative Product Along Axis 0:")
print(np.cumprod(data, axis=0))

print("\nCumulative Product Along Axis 1:")
print(np.cumprod(data, axis=1))

print("\nCumulative Product Along Axis 2:")
print(np.cumprod(data, axis=2))

# Difference
print("\nDifference Along Axis 0:")
print(np.diff(data, axis=0))

print("\nDifference Along Axis 1:")
print(np.diff(data, axis=1))

print("\nDifference Along Axis 2:")
print(np.diff(data, axis=2))

# Sorting
print("\nSorted Along Axis 0:")
print(np.sort(data, axis=0))

print("\nSorted Along Axis 1:")
print(np.sort(data, axis=1))

print("\nSorted Along Axis 2:")
print(np.sort(data, axis=2))

# Index of Minimum
print("\nIndex of Minimum Along Axis 0:")
print(np.argmin(data, axis=0))

print("\nIndex of Minimum Along Axis 1:")
print(np.argmin(data, axis=1))

print("\nIndex of Minimum Along Axis 2:")
print(np.argmin(data, axis=2))

# Index of Maximum
print("\nIndex of Maximum Along Axis 0:")
print(np.argmax(data, axis=0))

print("\nIndex of Maximum Along Axis 1:")
print(np.argmax(data, axis=1))

print("\nIndex of Maximum Along Axis 2:")
print(np.argmax(data, axis=2))

Dataset:
[[[10 20 30 40]
  [15 25 35 45]
  [20 30 40 50]]

 [[12 22 32 42]
  [17 27 37 47]
  [22 32 42 52]]]

Shape: (2, 3, 4)
Number of Dimensions: 3
Total Elements: 24

Sum of All Elements: 744
Sum Along Axis 0:
[[ 22  42  62  82]
 [ 32  52  72  92]
 [ 42  62  82 102]]
Sum Along Axis 1:
[[ 45  75 105 135]
 [ 51  81 111 141]]
Sum Along Axis 2:
[[100 120 140]
 [108 128 148]]

Mean of All Elements: 31.0
Mean Along Axis 0:
[[11. 21. 31. 41.]
 [16. 26. 36. 46.]
 [21. 31. 41. 51.]]
Mean Along Axis 1:
[[15. 25. 35. 45.]
 [17. 27. 37. 47.]]
Mean Along Axis 2:
[[25. 30. 35.]
 [27. 32. 37.]]

Median of All Elements: 31.0
Median Along Axis 0:
[[11. 21. 31. 41.]
 [16. 26. 36. 46.]
 [21. 31. 41. 51.]]
Median Along Axis 1:
[[15. 25. 35. 45.]
 [17. 27. 37. 47.]]
Median Along Axis 2:
[[25. 30. 35.]
 [27. 32. 37.]]

Minimum of All Elements: 10
Minimum Along Axis 0:
[[10 20 30 40]
 [15 25 35 45]
 [20 30 40 50]]
Minimum Along Axis 1:
[[10 20 30 40]
 [12 22 32 42]]
Minimum Along Axis 2:
[[10 15 20]
 [12